
POST http://localhost:8080/api/user/login 
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "123456"
}

###
POST http://localhost:8080/api/auth/signup HTTP/1.1
Content-Type: application/json

{
   "email": "john@gmail.com",
    "firstName": "John",
    "lastName": "Dall",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "ROLE_USER" 
}

### Add movie
POST http://localhost:8080/api/movies/add HTTP/1.1
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTYzMjAyNDI2MywiZXhwIjoxNjMyMDI3ODYzfQ.39i4jbcBTX-DXgyIwySvn8az9GMVR0es4niRdlamNKU

{
    "title": "batman",
    "year": "2050",
    "runtime": "230min"
}

### Search all users
GET http://localhost:8080/api/user
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTYzMjAxNDg2MSwiZXhwIjoxNjMyMDE4NDYxfQ.AN3y47kd4ZRz-fgK8B2GjF1yVO7bTlLx5AvDBWahPPo

### Search title movie
GET http://localhost:8080/api/movies/?title=batman forever
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTYzMjAyNDI2MywiZXhwIjoxNjMyMDI3ODYzfQ.39i4jbcBTX-DXgyIwySvn8az9GMVR0es4niRdlamNKU

### Update Movie
PUT http://localhost:8080/api/movies/update/6146b6e320024f6ab3d0745c
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTYzMjAyNDI2MywiZXhwIjoxNjMyMDI3ODYzfQ.39i4jbcBTX-DXgyIwySvn8az9GMVR0es4niRdlamNKU

{
    "title": "batman forever",
    "year": "2050",
    "runtime": "2050min"
}

### Delete Movie
DELETE http://localhost:8080/api/movies/delete/6146691d56c0a30c2f255fab
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTYzMjAyNDI2MywiZXhwIjoxNjMyMDI3ODYzfQ.39i4jbcBTX-DXgyIwySvn8az9GMVR0es4niRdlamNKU